FROM alpine AS qemu

#QEMU Download
ENV QEMU_URL https://github.com/balena-io/qemu/releases/download/v4.0.0%2Bbalena2/qemu-4.0.0.balena2-arm.tar.gz
RUN apk add curl && curl -L ${QEMU_URL} | tar zxvf - -C . --strip-components 1

FROM arm32v7/debian:bullseye-slim
COPY --from=qemu qemu-arm-static /usr/bin
RUN apt-get update && apt-get --yes install python3-all python3-pip python3-setuptools build-essential devscripts debhelper debmake dh-python